name: personal_expanses_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  async_builder: ^1.3.1
  rxdart: ^0.27.5
  permission_handler: ^10.2.0
  uuid: ^3.0.7
  http: ^0.13.5
  get_it: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate:
    true

  uses-material-design: true
